// src/pages/components/Skill.vue
<script setup lang="ts">
import SkillGraph from './SkillGraph.vue'
</script>

<template>
  <div class="home-section" text-center>
    <h3 class="home-section-title">
      <p>我热爱编程</p>
      <p>
        相信优雅的代码和艺术<span class="home-section-title-magic">可以改变人们的生活</span>
      </p>
    </h3>

    <h3 class="home-section-title">
      <p>我钟爱挑战</p>
      <p>
        认为不断尝试和勇于探索<span class="home-section-title-magic">可以让我们成长</span>
      </p>
    </h3>

    <div mt-15 overflow-x-auto overflow-y-hidden>
      <SkillGraph
        h-80 w-155 mx-auto
        lg:w-full lg:h-35vh
      />
    </div>
  </div>
</template>

// src/app/[locale]/(home)/components/Skill.tsx
import classNames from 'classnames';

import dynamic from 'next/dynamic';
import { useTranslations } from 'next-intl';

const SkillGraph = dynamic(() => import('./SkillGraph'), {
  ssr: false,
});

const HomeSkill = () => {
  const t = useTranslations('home');

  return (
    <div className="home-section content h-screen text-center">
      <h3 className="home-section-title">
        <p>{t('skill.coding.title')}</p>
        <p>
          {t('skill.coding.believe')}
          <span className="home-section-title-magic">
            {t('skill.coding.change-life')}
          </span>
        </p>
      </h3>

      <h3 className="home-section-title">
        <p>{t('skill.challenge.title')}</p>
        <p>
          {t('skill.challenge.try-and-explore')}
          <span className="home-section-title-magic">
            {t('skill.challenge.growth')}
          </span>
        </p>
      </h3>

      <div className="mt-12 overflow-hidden">
        <SkillGraph
          className={classNames('w-170 h-80', 'max-md:w-full max-md:h-30')}
        />
      </div>
    </div>
  );
};

export default HomeSkill;
