// src/app/[locale]/(home)/components/Photo.tsx
import Image from 'next/image';

import { useTranslations } from 'next-intl';

import classNames from 'classnames';

import config from 'config';

const PHOTOS = config.data.gallery.homePhotos;

const HomePhoto = () => {
  const t = useTranslations('home');

  return (
    <div className="home-section content text-center mb-10">
      <h3 className="home-section-title">
        <p>
          {t('photography.title.soul-and-body')}
          <span className="home-section-title-magic">
            {t('photography.title.one-the-way')}
          </span>
        </p>
        <p>{t('photography.title.together')}</p>
      </h3>

      <ul
        className={classNames(
          'mt-10 -mx-1',
          'flex justify-center flex-wrap',
          'animate-sway',
          'text-lg text-center lg:text-xl',
        )}
      >
        {PHOTOS.map((item, index) => (
          <li
            key={index}
            className={classNames(
              'relative m-1',
              'sm:h-24 md:h-32 h-48',
              'rounded overflow-hidden',
            )}
          >
            {/* <Image src={item.thumb} alt={item.name} /> */}
            <img src={item.thumb} alt={item.name} />
            <label
              className="absolute bottom-3 left-4 text-white"
              style={{ textShadow: '0 0 6px #333' }}
            >
              {item.name}
            </label>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default HomePhoto;

// src/pages/components/Photo.vue
<script setup lang="ts">
const photos = [
  {
    name: '自然',
    thumb: '/photos/nature.jpg',
  },
  {
    name: '雪山',
    thumb: '/photos/mountain-1.jpg',
  },
  {
    name: '建筑',
    thumb: '/photos/building.jpg',
  },
  {
    name: '街头',
    thumb: '/photos/city.jpg',
  },
  {
    name: '城市',
    thumb: '/photos/city-1.jpg',
  },
  {
    name: '人',
    thumb: '/photos/people.jpg',
  },
  {
    name: '海',
    thumb: '/photos/sea.jpg',
  },
  {
    name: '夜晚',
    thumb: '/photos/night.jpg',
  },
]
</script>

<template>
  <div class="home-section">
    <h3 class="home-section-title">
      <p>
        灵魂和身体<span class="home-section-title-magic">总有一个要在路上</span>
      </p>
      <p>而我，更想让它们相伴而行</p>
    </h3>

    <ul
      flex="~ wrap"
      justify-center
      m="t-10 -x-2"
      animate="sway count-infinite alternate"
      cursor-not-allowed
    >
      <li
        v-for="item of photos"
        :key="item.name"
        class="photo-item"
        relative m-2
        h="20 lg:100 xl:180"
        rounded="md lg:lg" overflow-hidden
        after:absolute after:left-0 after:top-0
        after:content-none after:w-full after:h-full
      >
        <img
          :src="item.thumb"
          :alt="item.name"
        >
        <label
          pos="absolute bottom-2 left-3"
          text="white shadow-sm"
        >
          {{ item.name }}
        </label>
      </li>
    </ul>
  </div>
</template>

<style>
.photo-item::after {
  box-shadow: inset 0 0 30px rgba(0, 0, 0, 0.6);
}
</style>
