// src/components/Header.vue
<script setup lang="ts">
import { isDark, toggleDark } from '~/composables'
const route = useRoute()
const { t } = useI18n()

const menus = [
  { id: 'HOME', title: t('header.nav.home'), link: '/', isActive: () => route.path === '/' },
  { id: 'BLOG', title: t('header.nav.blog'), link: '/blog', isActive: () => route.path.startsWith('/blog') },
  // { id: 'GALLERY', title: t('header.nav.gallery'), link: '/gallery', isActive: () => route.path === '/' },
  { id: 'ABOUT', title: t('header.nav.about'), link: '/about', isActive: () => route.path === '/about' },
  // { id: 'SAY_HI', title: t('header.nav.say-hi'), link: '/say-hi', isActive: () => route.path === '/say-hi' },
]

// const toggleLocales = () => {
//   // change to some real logic
//   const locales = availableLocales
//   locale.value = locales[(locales.indexOf(locale.value) + 1) % locales.length]
// }
</script>

<template>
  <header
    wrapper z-30 bg-light-soft dark:bg-slate-800 bg-opacity-98 dark:bg-opacity-98
    flex justify-between items-center
  >
    <RouterLink
      to="/"
      lt-sm="whitespace-pre-line leading-none"
      p="x-2 y-0.5"
      bg-brand rounded-lg
      font-bold font-mono
      text-sm text-white italic
      hover:opacity-80
      sm:text-md
      style="word-spacing: -0.3em;"
      :title="t('header.name')"
    >
      {{ t('header.slogan') }}
    </RouterLink>

    <nav flex overflow-x-hidden>
      <ul ml-5 flex overflow-x-auto whitespace-nowrap items-center>
        <li
          v-for="item of menus" :key="item.id"
          not-last:mr-5
        >
          <RouterLink
            v-slot="{ href, navigate }"
            custom
            :to="item.link"
          >
            <a
              hover:opacity-100
              hover:font-bold
              :href="href"
              :class="item.isActive() ? ['opacity-100', 'font-bold'] : ['opacity-50']"
              @click="navigate"
            >
              {{ item.title }}
            </a>
          </RouterLink>
        </li>
      </ul>

      <ul ml-5 flex items-center>
        <li
          not-last:mr-5
          opacity-50 cursor-pointer
          hover:opacity-100 hover:font-bold
          i-carbon-sun dark:i-carbon-moon
          :title="t('header.button.toggle-mode')"
          @click="toggleDark()"
        />
      </ul>
    </nav>
  </header>
</template>

// _pages/components/Header.tsx
import { CSSProperties } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import classNames from "classnames";
import { SunOne } from "@icon-park/react";

interface HeaderProps {
  className?: string;
  style?: CSSProperties;
}

const Header = ({ className, style }: HeaderProps) => {
  const router = useRouter();
  const { t } = useTranslation("common");

  console.log(router);

  const menus = [
    {
      id: "HOME",
      title: t("header.nav.home"),
      link: "/",
      isActive: () => router.pathname === "/",
    },
    // {
    //   id: "BLOG",
    //   title: t("header.nav.blog"),
    //   link: "/blog",
    //   isActive: () => router.pathname.startsWith("/blog"),
    // },
    // {
    //   id: "GALLERY",
    //   title: t("header.nav.gallery"),
    //   link: "/gallery",
    //   isActive: () => router.pathname === "/gallery",
    // },
    {
      id: "ABOUT",
      title: t("header.nav.about"),
      link: "/about",
      isActive: () => router.pathname === "/about",
    },
    {
      id: "SAY_HI",
      title: t("header.nav.say-hi"),
      link: "/#say-hi",
      isActive: () => router.pathname === "/say-hi",
    },
  ] as const;

  return (
    <header
      className={classNames(
        "wrapper flex justify-between items-center",
        "z-50 bg-light-soft bg-opacity-98",
        "dark:bg-slate-800 dark:bg-opacity-98",
        className,
      )}
      style={style}
    >
      <Link
        href="/"
        className={classNames(
          "px-2 py-0.5",
          "bg-brand rounded-lg",
          "font-bold font-mono text-sm text-white italic sm:text-md",
          "hover:opacity-80",
          "max-sm:whitespace-pre-line max-sm:leading-none",
        )}
        title={t("header.name")}
      >
        {t("header.slogan")}
      </Link>

      <nav className="flex overflow-hidden">
        <ul className="ml-5 flex overflow-x-auto whitespace-nowrap items-center">
          {menus.map((item) => (
            <li
              key={item.id}
              className={classNames(
                "mr-5 last:mr-0 opacity-50 hover:opacity-100 hover:font-bold",
                {
                  "font-bold": item.isActive(),
                  "opacity-100": item.isActive(),
                },
              )}
            >
              <Link href={item.link}>{item.title}</Link>
            </li>
          ))}
        </ul>

        <ul className="ml-5 flex items-center">
          <li
            className="last:mr-5 last:mr-0 opacity-50 cursor-pointer hover:opacity-100 hover:font-bold"
            title={t("header.button.toggle-mode")}
          >
            <SunOne theme="outline" size="20" />
          </li>
        </ul>
      </nav>
    </header>
  );
};

export default Header;
